In [3]:
import numpy as np

# Fuzzy sets
A = np.array([0.6, 0.8, 0.9])
B = np.array([0.5, 0.7, 0.4])

# Union
print("Union:", np.maximum(A, B))

# Intersection
print("Intersection:", np.minimum(A, B))

# Complement
print("Complement of A:", 1 - A)

# Difference
print("Difference A - B:", np.minimum(A, 1 - B))

# Cartesian Product
relation1 = np.minimum(A[:, None], B[None, :])
relation2 = np.minimum(B[:, None], A[None, :])
print("Relation (A x B):\n", relation1)
print("Relation (B x A):\n", relation2)

# Max-Min Composition
comp = np.zeros((relation1.shape[0], relation2.shape[1]))
for i in range(comp.shape[0]):
    for j in range(comp.shape[1]):
        comp[i, j] = np.max(np.minimum(relation1[i, :], relation2[:, j]))

print("Max-Min Composition:\n", comp)

Union: [0.6 0.8 0.9]
Intersection: [0.5 0.7 0.4]
Complement of A: [0.4 0.2 0.1]
Difference A - B: [0.5 0.3 0.6]
Relation (A x B):
 [[0.5 0.6 0.4]
 [0.5 0.7 0.4]
 [0.5 0.7 0.4]]
Relation (B x A):
 [[0.5 0.5 0.5]
 [0.6 0.7 0.7]
 [0.4 0.4 0.4]]
Max-Min Composition:
 [[0.6 0.6 0.6]
 [0.6 0.7 0.7]
 [0.6 0.7 0.7]]
